### ISSUE TITLE
Allow adding files to existing directory

### ISSUE THREAD

**Issue by tab00** [nftstorage/nft.storage#1830] opened 2022-04-15 09:58 UTC
There may be times when we want to add files to an already uploaded directory. Currently there is no function in nft.storage (API, web interface, or NFTUp) that allows this.

The way it works in IPFS Desktop is: open the directory to view the files in it, then from a file manager drag and drop new files in. I noticed it appears that the directory has a new CID after the files are uploaded. In reality the directory is "duplicated" with the new duplicate showing the newly-added files. Both the old and new directories are still accessible via their corresponding CID (even though IPFS Desktop makes it appear as if there was just one directory that was updated and its CID changed). It's a bit quirky but is still better than nothing, as users may accept that a new CID needs to be used to access both old and new files in the directory.

A particular use case could be in the https://nft.storage/files page - we may want to upload files of a collection at different times rather than all at once, and want to keep all files neatly, e.g. one directory per collection. Currently there is `storeDirectory` in the API but no function to later add files into the "same" directory. So we'd end up having multiple directories of different files if we upload on different occasions. We may rather see only one directory in the files web interface (whose CID may change after each occasion of file addition) containing all files than multiple directories each containing different files.

**Comment by dchoi27** [comment] 2022-04-19 16:42
Hey - I think there's a bit of a misunderstanding here on how IPFS works. There is no notion of adding a file to a directory - you correctly identify in your second paragraph that a new directory that contains another directory has a completely different CID, but it's not "quirky" - it's by definition how IPFS works (hashing the entire set of contents), so a feature, not a bug. 

We're tracking the feature request related to what you get in IPFS Desktop called MFS (https://docs.ipfs.io/concepts/file-systems/#mutable-file-system-mfs) here: https://github.com/nftstorage/nft.storage/issues/1175 Closing this one!

One note - even in a world with MFS, the Files page will likely always show the full set of uploads (the case outlined in this issue is more of an edge case).

**Closed by dchoi27** 2022-04-19 16:42 UTC
