### ISSUE TITLE
Cannot find module @web-std, after latest version release of this dependency

### ISSUE THREAD

**Issue by u-ajmal** [nftstorage/nft.storage#1166] opened 2022-01-25 17:57 UTC
### Use case

I am using nft.storage to upload nft to IPFS. There wasn't any issue earlier on, it just came up with the latest deployment we did. Each time a new deployment is done node modules are installed again.

Here is the package.json:

> {
  "name": "nft-management-backend",
  "version": "0.1.0",
  "description": "Backend APIs related to nft management",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/temp/nft-management-backend.git"
  },
  "dependencies": {
    "@types/node": "^16.10.2",
    "nft.storage": "^5.2.0",
  },
}

### Error returned

```
{
     "errorType": "Runtime.ImportModuleError",
     "errorMessage": "Error: Cannot find module '/var/task/node_modules/@web-std/fetch/dist/index.cjs'",
       "stack": [
           "Runtime.ImportModuleError: Error: Cannot find module '/var/task/node_modules/@web-std/fetch/dist/index.cjs'",
           "    at _loadUserApp (/var/runtime/UserFunction.js:202:13)",
           "    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)",
           "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
           "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
           "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
           "    at Module.load (internal/modules/cjs/loader.js:950:32)",
           "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
           "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
           "    at internal/main/run_main_module.js:17:47"
       ]
}
```

**Comment by iamserversurfer** [comment] 2022-01-26 19:36
I'm getting the same issue.

Do you know what version you were using before?

**Comment by u-ajmal** [comment] 2022-01-26 23:09
@iamserversurfer nft.storage version is the same but the dependent library @web-std got upgraded from 3.0.0 to 3.0.2. The upgrade needs to be handled appropriately. I had to downgrade nft.storage to version 4.0.1 for my functionality to work.

**Comment by alanshaw** [comment] 2022-01-27 22:37
@Gozala any chance you can look into this? Looks like the commonjs version didn't get published with the latest release.

**Comment by Gozala** [comment] 2022-01-28 16:44
Looks like this change  https://github.com/web-std/io/pull/35 introduced regression by leaving out that file from npm.

**Comment by Gozala** [comment] 2022-01-28 22:38
@u-ajmal should be fixed now, please reopen if you still encounter this.

**Closed by Gozala** 2022-01-28 22:38 UTC
Labels: kind/bug, need/triage

**Comment by anudit** [comment] 2022-01-31 06:53
@Gozala  Still getting this in `"nft.storage": "^5.2.2"`
