### ISSUE TITLE
Error while importing on Angular 12

### ISSUE THREAD

**Issue by samuel-videau** [nftstorage/nft.storage#720] opened 2021-11-03 15:04 UTC
Hi !

I'm trying to import nftStorage in my Angular 12 application, just like this : 
`import { NFTStorage } from 'nft.storage'
`

And i get a 'Failed to compile' : 
```
Error: node_modules/nft.storage/dist/src/token.d.ts:13:36 - error TS2344: Type '(input: Blob) => URL' does not satisfy the constraint '((input: unknown) => unknown) | ((input: unknown) => unknown)'.
  Type '(input: Blob) => URL' is not assignable to type '(input: unknown) => unknown'.
    Types of parameters 'input' and 'input' are incompatible.
      Type 'unknown' is not assignable to type 'Blob'.

13         data: API.MatchRecord<T_1, (input: Blob) => URL>;
```

Any idea how to fix this ?

Thanks in advance.

**Comment by 5t41k3r** [comment] 2021-11-06 06:24
Very interesting, I too am trying to use NFT.Storage with Angular 12 and I am getting the same error. 
Did you get this running?

**Comment by samuel-videau** [comment] 2021-11-06 14:12
@5t41k3r I finally used a post request to do it, as I'm not sure we can fix the issue, here is the code : 

```
public async uploadMetadata(file: File): Promise<string> {
    const response = await fetch('https://api.nft.storage/upload', {
      method: 'POST',
      body: file,
      headers: {'Authorization': 'Bearer ' + nftStorageKey}
    });

    const data = await response.json();
    console.log(data);

    return 'ipfs://' + data.value.cid;
  }
```

**Comment by dchoi27** [comment] 2021-11-09 08:42
@Gozala any thoughts?

**Comment by dashcraft** [comment] 2021-11-24 15:48
I spun up a codesandbox using angular 12 and used the dependencies and devDependencies mentioned @5t41k3r and was
unable to reproduce. https://codesandbox.io/s/nft-angular-12-3zpfz?file=/package.json

Can you create a minimal reproducible project using angular 12 using codesandbox or a public git repo, so we can further debug.

**Comment by dashcraft** [comment] 2021-11-24 15:50
I spun up a codesandbox using angular 12 and used the dependencies and devDependencies mentioned @5t41k3r and was
unable to reproduce. https://codesandbox.io/s/nft-angular-12-3zpfz?file=/package.json

Can you create a minimal reproducible project using angular 12 using codesandbox or a public git repo, so we can further debug.

**Comment by JeffLowe** [comment] 2022-01-21 14:54
Closing this out for now.  Feel free to reopen, comment, or submit a new ticket if you run into any further issues.

**Closed by JeffLowe** 2022-01-21 14:54 UTC
Labels: kind/bug, P2, need/author-input, topic/tg
